# 15.1.3. 获取复杂错误场景的回溯

[![error-chain-badge]][error-chain] [![cat-rust-patterns-badge]][cat-rust-patterns]

本实例展示了如何处理一个复杂的错误场景，并且打印出错误回溯。依赖于 [`chain_err`]，通过附加新的错误来扩展错误信息。从而可以展开错误堆栈，这样提供了更好的上下文来理解错误的产生原因。

下述代码尝试将值 `256` 反序列化为 `u8`。首先 Serde 产生错误，然后是 csv，最后是用户代码。

```rust,edition2018
{{ #include ../../../examples/errors/handle/examples/backtrace.rs }}
```

错误回溯信息如下：

```text
Error level - description
└> 0 - Cannot read CSV data
└> 1 - Cannot deserialize RGB color
└> 2 - CSV deserialize error: record 1 (line: 2, byte: 15): field 1: number too large to fit in target type
└> 3 - field 1: number too large to fit in target type
```

可以通过附加命令参数 `RUST_BACKTRACE=1` 运行实例，以显示与此错误相关的详细[回溯][`backtrace`]。

[`backtrace`]: https://docs.rs/error-chain/*/error_chain/trait.ChainedError.html#tymethod.backtrace
[`chain_err`]: https://docs.rs/error-chain/*/error_chain/index.html#chaining-errors

{{#include ../../links.md}}
